### ISSUE TITLE
VS Crashed when trying to add a library

### ISSUE THREAD

**Issue by kelps** [madskristensen/Packman#37]
### Installed product versions
- Visual Studio Enterprise 2015 14.0.25123.00 Update 2
- Client-Side Library Installer: example 1.2.117

### Description
Visual Studio is Crashing when I try to add a client side library. 

### Steps to recreate
1. New or empty web project (.NET 4.5)
2. create js folder
3. right click js folder and click "Add client-side library..."
4. popup window opens and VS crashes right after with messeges "Visual Studio Stopped Working" and then the "Restarting" popup).

I tried on different projects and solutions to see if the problems was with a specific project or .NET target, but got the same results. Haven't tried on other computers yet.

Here are the logs there were added to my EventLog when VS Crashed.

[eventlog vs crash add client-side lib.zip](https://github.com/madskristensen/Packman/files/264607/eventlog.vs.crash.add.client-side.lib.zip)

**Comment by kelps** [comment]
Follow up:
I was able to add the package I wanted by manually creating the packman.json file, but only after I went into Tool > Options and changed the provider to JsDelivr instead of Cdnjs. But the UI is still crashing even after that configuration change.

I got the following error in the output window before I changed the provider:

14/05/2016 13:59:01: Packman.PackageNotFoundException: Exception of type 'Packman.PackageNotFoundException' was thrown.
   at Packman.Manager.<InstallAll>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PackmanVsix.PackageService.<RestorePackagesAsync>d__4.MoveNext() in C:\projects\packman\src\PackmanVsix\PackageService.cs:line 49

**Comment by kelps** [comment]
###Follow up 2:
I just tried on another computer with the same project and it worked. There must be some conflict on my main computer, but it is bad that it crashed so hard that VS got closed. May need some better error handling. Feel free to ping me if you decide to track this down but can't reproduce.

**Comment by tlk** [comment]
This extension now consistently crashes VS2015 when I right-click a folder to add a client side library. v1.2.117

![image](https://cloud.githubusercontent.com/assets/90870/16153238/c6e2e9fa-34a5-11e6-89a6-bae0370941e4.png)

```
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in PresentationFramework.dll
Additional information: Object reference not set to an instance of an object.
```

**Comment by madskristensen** [comment]
It may be happening when/if CDNJS is down for maintenance or something like that.

**Comment by o0MrBlack0o** [comment]
delete %userprofile%\.packman folder .It work for me :)

**Comment by xperiandri** [comment]
``` C#
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Packman.Manifest+<FromFileOrNewAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Packman.Manager+<Install>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PackmanVsix.PackageService+<InstallpackageAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PackmanVsix.InstallPackageCommand+<Install>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by xperiandri** [comment]
I deleted but it appeared again
