### ISSUE TITLE
Not installable on any currently installed products.

### ISSUE THREAD

**Issue by barbedCoil** [madskristensen/Packman#49]
### Installed product versions
- Visual Studio: [2017 Professional - v15.7.6]
- This extension: [v1.2.130]

### Description
Searching for applicable products...
Found installed product - Global Location
Found installed product - ssms
Found installed product - Visual Studio Professional 2017
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### Steps to recreate
1. Downloaded installer
2. Run vsix installer

### Current behavior
This extension is not installable on any currently installed products.

### Expected behavior
Install.

**Comment by jerone** [comment]
To quote [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Client-SideLibraryInstaller) for this package:

> **DEPRECATED** Visual Studio 2017 Update 7 includes Library Manager which is maintained on github.com/aspnet/LibraryManager. Use only this extension on Visual Studio 2015

**Comment by barbedCoil** [comment]
Thanks, I missed that.

On September 9, 2018 8:42:33 AM MST, Jeroen van Warmerdam <notifications@github.com> wrote:
>To quote [Visual Studio
>Marketplace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Client-SideLibraryInstaller)
>for this package:
>
>> **DEPRECATED** Visual Studio 2017 Update 7 includes Library Manager
>which is maintained on github.com/aspnet/LibraryManager. Use only this
>extension on Visual Studio 2015
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/madskristensen/Packman/issues/49#issuecomment-419724533

-- 
Tab
